[package]
name = "d1-linux-embedded"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpplib = { path = "../cpplib" }
linux-embedded-hal = { version = "0.3", features = ["gpio_cdev"] }
